name: read traffic
on:
  schedule:
  - cron: "1/5 * * * *"
  
jobs:
  create_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: clones
      run: |
        curl --request GET \
        --url https://api.github.com/repos/${{ github.repository }}/traffic/clones \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
    - name: views
      run: |
        pip install requests
        python read_views.py ${{ secrets.PASSWORD }}
    - name: ls
      run: ls
    - name: push      
      run: 
        git config --global user.name 'ChristophKirst'
        git config --global user.email 'christoph.kirst.ck@gmail.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout "${GITHUB_REF:11}"
        git commit -am "automatic count views"
        git push
        

